//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public Box()
        {
            this.ReceivedProducts = new HashSet<ReceivedProduct>();
            this.Transfers = new HashSet<Transfer>();
        }
    
        public Nullable<bool> IsWaste { get; set; }
        public Nullable<bool> Reevaluate { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public Nullable<bool> Transit { get; set; }
        public long BoxID { get; set; }
        public long IDProduct { get; set; }
        public System.DateTime AdquisitionDate { get; set; }
        public long Quantity { get; set; }
        public decimal BuyerCost { get; set; }
        public long IDStatus { get; set; }
        public Nullable<long> IDPack { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> IDSale { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Depth { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual ItemsState ItemsState { get; set; }
        public virtual Pack Pack { get; set; }
        public virtual ICollection<ReceivedProduct> ReceivedProducts { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
