//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Clients = new HashSet<Client>();
            this.DistributionCenters = new HashSet<DistributionCenter>();
        }
    
        public long CityID { get; set; }
        public string ISO { get; set; }
        public string Name { get; set; }
        public long IDProvince { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string DbID { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<DistributionCenter> DistributionCenters { get; set; }
    }
}
