//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public long ClientsID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public string CUIT { get; set; }
        public long City { get; set; }
        public bool Deleted { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
