//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialAgreement
    {
        public CommercialAgreement()
        {
            this.Packs = new HashSet<Pack>();
        }
    
        public long CommercialAgreementID { get; set; }
        public long IDSuplier { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
    }
}
