//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public Container()
        {
            this.InternalBoxes = new HashSet<InternalBox>();
        }
    
        public long ContainerID { get; set; }
        public long IDContainerTypes { get; set; }
        public Nullable<long> IDTemporalDeposit { get; set; }
        public decimal UsedSpace { get; set; }
        public string Code { get; set; }
        public Nullable<long> IDShelfSubdivition { get; set; }
    
        public virtual ContainerType ContainerType { get; set; }
        public virtual TemporaryDeposit TemporaryDeposit { get; set; }
        public virtual ShelfsSubdivision ShelfsSubdivision { get; set; }
        public virtual ICollection<InternalBox> InternalBoxes { get; set; }
    }
}
