//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionCenter
    {
        public DistributionCenter()
        {
            this.Inventories = new HashSet<Inventory>();
            this.Receptions = new HashSet<Reception>();
            this.Sales = new HashSet<Sale>();
            this.Transfers = new HashSet<Transfer>();
            this.TransfersSend = new HashSet<Transfer>();
            this.Policies = new HashSet<Policy>();
            this.Notifications = new HashSet<Notification>();
            this.Users = new HashSet<User>();
        }
    
        public long DistributionCenterID { get; set; }
        public long IDCity { get; set; }
        public decimal UsableSpace { get; set; }
        public string Address { get; set; }
        public bool Deleted { get; set; }
        public string Telephone { get; set; }
        public decimal UsableUsedSpace { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Reception> Receptions { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual ICollection<Transfer> TransfersSend { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
