//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Stock_Invented = new HashSet<Stock_Invented>();
        }
    
        public string Code { get; set; }
        public long InventoryID { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public string InventoryName { get; set; }
        public long StoredProductsCount { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public decimal ValuesOfStoredProducts { get; set; }
        public long IDDistributionCenter { get; set; }
    
        public virtual DistributionCenter DistributionCenter { get; set; }
        public virtual ICollection<Stock_Invented> Stock_Invented { get; set; }
    }
}
