//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersValueSecurity
    {
        public string IDUser { get; set; }
        public Nullable<decimal> MinTotal { get; set; }
        public Nullable<decimal> MaxTotal { get; set; }
    
        public virtual User User { get; set; }
    }
}
