//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public Policy()
        {
            this.DistributionCenters = new HashSet<DistributionCenter>();
            this.Products = new HashSet<Product>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public long PoliciesID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DistributionCenter> DistributionCenters { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
