//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Policies = new HashSet<Policy>();
            this.Boxes = new HashSet<Box>();
            this.ProvidedBies = new HashSet<ProvidedBy>();
            this.CartItems = new HashSet<CartItem>();
        }
    
        public long ProductID { get; set; }
        public string Barcode { get; set; }
        public decimal Depth { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Size { get; set; }
        public long IDProductCategory { get; set; }
        public byte[] Photo { get; set; }
        public bool Deleted { get; set; }
        public decimal SellPrice { get; set; }
        public Nullable<long> MinStock { get; set; }
        public bool IsBasic { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual ICollection<ProvidedBy> ProvidedBies { get; set; }
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
