//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsValueSecurity
    {
        public ProductsValueSecurity()
        {
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public string IDUser { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
