//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
            this.ParentCategories = new HashSet<ProductCategory>();
            this.ChildrenCategories = new HashSet<ProductCategory>();
            this.Deposits = new HashSet<Deposit>();
            this.Sectors = new HashSet<Sector>();
            this.Halls = new HashSet<Hall>();
            this.Racks = new HashSet<Rack>();
            this.ProductsValueSecurities = new HashSet<ProductsValueSecurity>();
        }
    
        public long ProductCategoriesID { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductCategory> ParentCategories { get; set; }
        public virtual ICollection<ProductCategory> ChildrenCategories { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
        public virtual ICollection<Hall> Halls { get; set; }
        public virtual ICollection<Rack> Racks { get; set; }
        public virtual ICollection<ProductsValueSecurity> ProductsValueSecurities { get; set; }
    }
}
