//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidedBy
    {
        public ProvidedBy()
        {
            this.SupplierOrderItems = new HashSet<SupplierOrderItem>();
        }
    
        public long IDSupplier { get; set; }
        public long IDProduct { get; set; }
        public int ItemsPerBox { get; set; }
        public decimal BoxDepth { get; set; }
        public decimal BoxWidth { get; set; }
        public decimal BoxHeight { get; set; }
        public Nullable<decimal> BoxSize { get; set; }
        public decimal PurchasePrice { get; set; }
        public bool Inactive { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<SupplierOrderItem> SupplierOrderItems { get; set; }
    }
}
