//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rack
    {
        public Rack()
        {
            this.Shelfs = new HashSet<Shelf>();
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public long RackID { get; set; }
        public string Description { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal Depth { get; set; }
        public Nullable<decimal> Size { get; set; }
        public long IDHall { get; set; }
        public decimal UsedSpace { get; set; }
        public string RackCode { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual ICollection<Shelf> Shelfs { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
