//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public Reception()
        {
            this.ReceivedProducts1 = new HashSet<ReceivedProduct>();
        }
    
        public long ReceiveID { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public string IDSupplierOrder { get; set; }
        public Nullable<long> IDSupplier { get; set; }
        public long IDDistributionCenter { get; set; }
        public string COT { get; set; }
        public bool IsPurchase { get; set; }
    
        public virtual DistributionCenter DistributionCenter { get; set; }
        public virtual ICollection<ReceivedProduct> ReceivedProducts1 { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
    }
}
