//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Boxes = new HashSet<Box>();
        }
    
        public long SaleID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public long IDDistributionCenter { get; set; }
        public Nullable<long> IDClient { get; set; }
        public bool IsIncome { get; set; }
        public string COT { get; set; }
        public string BillNumber { get; set; }
        public bool Annulated { get; set; }
    
        public virtual DistributionCenter DistributionCenter { get; set; }
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual Client Client { get; set; }
    }
}
