//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Halls = new HashSet<Hall>();
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public long SectorID { get; set; }
        public string Description { get; set; }
        public decimal Width { get; set; }
        public decimal Depth { get; set; }
        public decimal Size { get; set; }
        public long IDDeposit { get; set; }
        public decimal UsableSpace { get; set; }
        public decimal UsedSpace { get; set; }
        public decimal UsedUsableSpace { get; set; }
    
        public virtual ICollection<Hall> Halls { get; set; }
        public virtual Deposit Deposit { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
