//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public Shelf()
        {
            this.ShelfsSubdivisions = new HashSet<ShelfsSubdivision>();
        }
    
        public long ShelfID { get; set; }
        public decimal Height { get; set; }
        public decimal Size { get; set; }
        public long IDRack { get; set; }
        public Nullable<int> ShelfNumber { get; set; }
        public decimal UsedSpace { get; set; }
    
        public virtual ICollection<ShelfsSubdivision> ShelfsSubdivisions { get; set; }
        public virtual Rack Rack { get; set; }
    }
}
