//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelfsSubdivision
    {
        public ShelfsSubdivision()
        {
            this.Containers = new HashSet<Container>();
        }
    
        public long ShelfSubdivisionID { get; set; }
        public decimal Width { get; set; }
        public decimal Size { get; set; }
        public long IDShelf { get; set; }
        public string DivitionCode { get; set; }
        public decimal UsedSpace { get; set; }
    
        public virtual Shelf Shelf { get; set; }
        public virtual ICollection<Container> Containers { get; set; }
    }
}
