//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.CommercialAgreements = new HashSet<CommercialAgreement>();
            this.ProvidedBies = new HashSet<ProvidedBy>();
            this.SupplierOrders = new HashSet<SupplierOrder>();
        }
    
        public long SupplierID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<CommercialAgreement> CommercialAgreements { get; set; }
        public virtual ICollection<ProvidedBy> ProvidedBies { get; set; }
        public virtual ICollection<SupplierOrder> SupplierOrders { get; set; }
    }
}
