//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        public SupplierOrder()
        {
            this.Receptions = new HashSet<Reception>();
            this.SupplierOrderItems = new HashSet<SupplierOrderItem>();
        }
    
        public string SupplierOrderID { get; set; }
        public long IDSupplier { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool Canceled { get; set; }
        public bool Received { get; set; }
    
        public virtual ICollection<Reception> Receptions { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<SupplierOrderItem> SupplierOrderItems { get; set; }
    }
}
