//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryDeposit
    {
        public TemporaryDeposit()
        {
            this.Containers = new HashSet<Container>();
        }
    
        public long TemporaryDepositID { get; set; }
        public string Description { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal Depth { get; set; }
        public Nullable<decimal> Size { get; set; }
        public long IDDistributionCenter { get; set; }
        public Nullable<int> Floor { get; set; }
        public decimal UsedSpace { get; set; }
    
        public virtual InternalDistributionCenter InternalDistributionCenter { get; set; }
        public virtual ICollection<Container> Containers { get; set; }
    }
}
