//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Box.
        /// </summary>
        public static string AddBox {
            get {
                return ResourceManager.GetString("AddBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Container.
        /// </summary>
        public static string AddContainer {
            get {
                return ResourceManager.GetString("AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Container&apos;s Type.
        /// </summary>
        public static string AddContainerType {
            get {
                return ResourceManager.GetString("AddContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Deposit.
        /// </summary>
        public static string AddDeposit {
            get {
                return ResourceManager.GetString("AddDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add External Distribution Center.
        /// </summary>
        public static string AddExternalDistributionCenter {
            get {
                return ResourceManager.GetString("AddExternalDistributionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hall.
        /// </summary>
        public static string AddHall {
            get {
                return ResourceManager.GetString("AddHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Internal Distribution Center.
        /// </summary>
        public static string AddInternalDistributionCenter {
            get {
                return ResourceManager.GetString("AddInternalDistributionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item State.
        /// </summary>
        public static string AddItemStates {
            get {
                return ResourceManager.GetString("AddItemStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Pack.
        /// </summary>
        public static string AddPack {
            get {
                return ResourceManager.GetString("AddPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rack.
        /// </summary>
        public static string AddRack {
            get {
                return ResourceManager.GetString("AddRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sector.
        /// </summary>
        public static string AddSector {
            get {
                return ResourceManager.GetString("AddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Temporal Deposit.
        /// </summary>
        public static string AddTemporaryDeposit {
            get {
                return ResourceManager.GetString("AddTemporaryDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Valuea Security Rule.
        /// </summary>
        public static string AddValueSecurity {
            get {
                return ResourceManager.GetString("AddValueSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asign Suppliers to Product.
        /// </summary>
        public static string AsignSuppliers {
            get {
                return ResourceManager.GetString("AsignSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignations.
        /// </summary>
        public static string Assignations {
            get {
                return ResourceManager.GetString("Assignations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Roles.
        /// </summary>
        public static string AssignRoles {
            get {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to Distribution Center.
        /// </summary>
        public static string AssignToDistributionCenter {
            get {
                return ResourceManager.GetString("AssignToDistributionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes Administration.
        /// </summary>
        public static string BoxesAdmin {
            get {
                return ResourceManager.GetString("BoxesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Administration.
        /// </summary>
        public static string CategoryAdmin {
            get {
                return ResourceManager.GetString("CategoryAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Password.
        /// </summary>
        public static string ChangeUserPassword {
            get {
                return ResourceManager.GetString("ChangeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients&apos; Administration.
        /// </summary>
        public static string ClientsAdmin {
            get {
                return ResourceManager.GetString("ClientsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Administration.
        /// </summary>
        public static string ContainersAdmin {
            get {
                return ResourceManager.GetString("ContainersAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers Types Administration.
        /// </summary>
        public static string ContainersTypesAdmin {
            get {
                return ResourceManager.GetString("ContainersTypesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Inventory.
        /// </summary>
        public static string CreateInventory {
            get {
                return ResourceManager.GetString("CreateInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits Administration.
        /// </summary>
        public static string DepositsABM {
            get {
                return ResourceManager.GetString("DepositsABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center Details.
        /// </summary>
        public static string DetailsPerDC {
            get {
                return ResourceManager.GetString("DetailsPerDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Centers Administration.
        /// </summary>
        public static string DistributionCenterABM {
            get {
                return ResourceManager.GetString("DistributionCenterABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Centers.
        /// </summary>
        public static string DistributionCenters {
            get {
                return ResourceManager.GetString("DistributionCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Last Inventory.
        /// </summary>
        public static string EditLastInventory {
            get {
                return ResourceManager.GetString("EditLastInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roles.
        /// </summary>
        public static string EditRoles {
            get {
                return ResourceManager.GetString("EditRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Menu.
        /// </summary>
        public static string FixMenu {
            get {
                return ResourceManager.GetString("FixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halls.
        /// </summary>
        public static string Halls {
            get {
                return ResourceManager.GetString("Halls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halls Administration.
        /// </summary>
        public static string HallsABM {
            get {
                return ResourceManager.GetString("HallsABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items States&apos; Administration.
        /// </summary>
        public static string ItemsStatesABM {
            get {
                return ResourceManager.GetString("ItemsStatesABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item States.
        /// </summary>
        public static string ItemStates {
            get {
                return ResourceManager.GetString("ItemStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packs.
        /// </summary>
        public static string Packs {
            get {
                return ResourceManager.GetString("Packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packs&apos; Administration.
        /// </summary>
        public static string PacksABM {
            get {
                return ResourceManager.GetString("PacksABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Administration.
        /// </summary>
        public static string ProductAdmin {
            get {
                return ResourceManager.GetString("ProductAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks.
        /// </summary>
        public static string Racks {
            get {
                return ResourceManager.GetString("Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks Administration.
        /// </summary>
        public static string RacksABM {
            get {
                return ResourceManager.GetString("RacksABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Reception.
        /// </summary>
        public static string Receptions {
            get {
                return ResourceManager.GetString("Receptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Asignation.
        /// </summary>
        public static string RoleAsignation {
            get {
                return ResourceManager.GetString("RoleAsignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Administration.
        /// </summary>
        public static string RolesAdmin {
            get {
                return ResourceManager.GetString("RolesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors Administration.
        /// </summary>
        public static string SectorsABM {
            get {
                return ResourceManager.GetString("SectorsABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Policies.
        /// </summary>
        public static string SecurityPolicies {
            get {
                return ResourceManager.GetString("SecurityPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers Administration.
        /// </summary>
        public static string SupplierAdmin {
            get {
                return ResourceManager.GetString("SupplierAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal Deposits Administration.
        /// </summary>
        public static string TemporalDepositsABM {
            get {
                return ResourceManager.GetString("TemporalDepositsABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfix Menu.
        /// </summary>
        public static string UnfixMenu {
            get {
                return ResourceManager.GetString("UnfixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Administration.
        /// </summary>
        public static string UsersAdmin {
            get {
                return ResourceManager.GetString("UsersAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Roles Asignation.
        /// </summary>
        public static string UsersRolesAdmin {
            get {
                return ResourceManager.GetString("UsersRolesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Security.
        /// </summary>
        public static string ValueSecurity {
            get {
                return ResourceManager.GetString("ValueSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Last Inventory.
        /// </summary>
        public static string ViewLastInventory {
            get {
                return ResourceManager.GetString("ViewLastInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Roles.
        /// </summary>
        public static string ViewRoles {
            get {
                return ResourceManager.GetString("ViewRoles", resourceCulture);
            }
        }
    }
}
