//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boxes.
        /// </summary>
        public static string BoxesWArt {
            get {
                return ResourceManager.GetString("BoxesWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Box.
        /// </summary>
        public static string BoxWArt {
            get {
                return ResourceManager.GetString("BoxWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Category.
        /// </summary>
        public static string CategoryChild {
            get {
                return ResourceManager.GetString("CategoryChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Child Category.
        /// </summary>
        public static string CategoryChildWArt {
            get {
                return ResourceManager.GetString("CategoryChildWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string CategoryParent {
            get {
                return ResourceManager.GetString("CategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Parent Category.
        /// </summary>
        public static string CategoryParentWArt {
            get {
                return ResourceManager.GetString("CategoryParentWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category.
        /// </summary>
        public static string CategoryWArt {
            get {
                return ResourceManager.GetString("CategoryWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Client.
        /// </summary>
        public static string ClientWArt {
            get {
                return ResourceManager.GetString("ClientWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial Agreements.
        /// </summary>
        public static string CommercialAgreements {
            get {
                return ResourceManager.GetString("CommercialAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Type.
        /// </summary>
        public static string ContainerType {
            get {
                return ResourceManager.GetString("ContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Container Type.
        /// </summary>
        public static string ContainerTypeWArt {
            get {
                return ResourceManager.GetString("ContainerTypeWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Container.
        /// </summary>
        public static string ContainerWArt {
            get {
                return ResourceManager.GetString("ContainerWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deposit.
        /// </summary>
        public static string DepositWArt {
            get {
                return ResourceManager.GetString("DepositWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center.
        /// </summary>
        public static string DistributionCenter {
            get {
                return ResourceManager.GetString("DistributionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Distribution Centers.
        /// </summary>
        public static string DistributionCentersWArt {
            get {
                return ResourceManager.GetString("DistributionCentersWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Distribution Center.
        /// </summary>
        public static string DistributionCenterWArt {
            get {
                return ResourceManager.GetString("DistributionCenterWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divition.
        /// </summary>
        public static string Divition {
            get {
                return ResourceManager.GetString("Divition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Divition.
        /// </summary>
        public static string DivitionWArt {
            get {
                return ResourceManager.GetString("DivitionWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hall.
        /// </summary>
        public static string HallWArt {
            get {
                return ResourceManager.GetString("HallWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inventory.
        /// </summary>
        public static string InventoryWArt {
            get {
                return ResourceManager.GetString("InventoryWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items Found: .
        /// </summary>
        public static string ItemsReturned {
            get {
                return ResourceManager.GetString("ItemsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s State.
        /// </summary>
        public static string ItemState {
            get {
                return ResourceManager.GetString("ItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item&apos;s State.
        /// </summary>
        public static string ItemStateWArt {
            get {
                return ResourceManager.GetString("ItemStateWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Notification.
        /// </summary>
        public static string NotificationWArt {
            get {
                return ResourceManager.GetString("NotificationWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order.
        /// </summary>
        public static string OrderWArt {
            get {
                return ResourceManager.GetString("OrderWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pack.
        /// </summary>
        public static string PackWArt {
            get {
                return ResourceManager.GetString("PackWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing, please wait....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Products.
        /// </summary>
        public static string ProductsWArt {
            get {
                return ResourceManager.GetString("ProductsWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product.
        /// </summary>
        public static string ProductWArt {
            get {
                return ResourceManager.GetString("ProductWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        public static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks.
        /// </summary>
        public static string Racks {
            get {
                return ResourceManager.GetString("Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Racks.
        /// </summary>
        public static string RacksWArt {
            get {
                return ResourceManager.GetString("RacksWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rack.
        /// </summary>
        public static string RackWArt {
            get {
                return ResourceManager.GetString("RackWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptions.
        /// </summary>
        public static string Receptions {
            get {
                return ResourceManager.GetString("Receptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rol.
        /// </summary>
        public static string RoleWArt {
            get {
                return ResourceManager.GetString("RoleWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rule.
        /// </summary>
        public static string RuleWArt {
            get {
                return ResourceManager.GetString("RuleWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sale.
        /// </summary>
        public static string SaleWArt {
            get {
                return ResourceManager.GetString("SaleWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sector.
        /// </summary>
        public static string SectorWArt {
            get {
                return ResourceManager.GetString("SectorWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Supplier.
        /// </summary>
        public static string SupplierWArt {
            get {
                return ResourceManager.GetString("SupplierWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Deposit.
        /// </summary>
        public static string TemporaryDeposit {
            get {
                return ResourceManager.GetString("TemporaryDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Temporary Deposit.
        /// </summary>
        public static string TemporaryDepositWArt {
            get {
                return ResourceManager.GetString("TemporaryDepositWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username.
        /// </summary>
        public static string UsernameWArt {
            get {
                return ResourceManager.GetString("UsernameWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Users.
        /// </summary>
        public static string UsersWArt {
            get {
                return ResourceManager.GetString("UsersWArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User.
        /// </summary>
        public static string UserWArt {
            get {
                return ResourceManager.GetString("UserWArt", resourceCulture);
            }
        }
    }
}
