//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penates.App_GlobalResources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelFormsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelFormsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_GlobalResources.Forms.ModelFormsResources", typeof(ModelFormsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Stream.
        /// </summary>
        public static string ActivityStream {
            get {
                return ResourceManager.GetString("ActivityStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adquisition Date.
        /// </summary>
        public static string AdquisitionDate {
            get {
                return ResourceManager.GetString("AdquisitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of products.
        /// </summary>
        public static string AmountOfProducts {
            get {
                return ResourceManager.GetString("AmountOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of proucts types.
        /// </summary>
        public static string AmountOfProductsTypes {
            get {
                return ResourceManager.GetString("AmountOfProductsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of space covered.
        /// </summary>
        public static string AverageOfSpaceCovered {
            get {
                return ResourceManager.GetString("AverageOfSpaceCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill&apos;s Number.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Box Depth.
        /// </summary>
        public static string BoxDepth {
            get {
                return ResourceManager.GetString("BoxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes Quantity.
        /// </summary>
        public static string BoxesQty {
            get {
                return ResourceManager.GetString("BoxesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Box Height.
        /// </summary>
        public static string BoxHeight {
            get {
                return ResourceManager.GetString("BoxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box ID.
        /// </summary>
        public static string BoxID {
            get {
                return ResourceManager.GetString("BoxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Box Size.
        /// </summary>
        public static string BoxSize {
            get {
                return ResourceManager.GetString("BoxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Box Width.
        /// </summary>
        public static string BoxWidth {
            get {
                return ResourceManager.GetString("BoxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer&apos;s Cost.
        /// </summary>
        public static string BuyerCost {
            get {
                return ResourceManager.GetString("BuyerCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Order.
        /// </summary>
        public static string CanceledOrder {
            get {
                return ResourceManager.GetString("CanceledOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City&apos;s Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Address.
        /// </summary>
        public static string ClientAddress {
            get {
                return ResourceManager.GetString("ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client City.
        /// </summary>
        public static string ClientCity {
            get {
                return ResourceManager.GetString("ClientCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Country.
        /// </summary>
        public static string ClientCountry {
            get {
                return ResourceManager.GetString("ClientCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s ID.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Province.
        /// </summary>
        public static string ClientProvince {
            get {
                return ResourceManager.GetString("ClientProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Telephone.
        /// </summary>
        public static string ClientTelephone {
            get {
                return ResourceManager.GetString("ClientTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container&apos;s Code.
        /// </summary>
        public static string ContainerCode {
            get {
                return ResourceManager.GetString("ContainerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container ID.
        /// </summary>
        public static string ContainerID {
            get {
                return ResourceManager.GetString("ContainerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Type Name.
        /// </summary>
        public static string ContainerTypeDescription {
            get {
                return ResourceManager.GetString("ContainerTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Type&apos;s ID.
        /// </summary>
        public static string ContainerTypeID {
            get {
                return ResourceManager.GetString("ContainerTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Type ID.
        /// </summary>
        public static string ContainerTypesID {
            get {
                return ResourceManager.GetString("ContainerTypesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COT Number.
        /// </summary>
        public static string COT {
            get {
                return ResourceManager.GetString("COT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        public static string CUIT {
            get {
                return ResourceManager.GetString("CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        public static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit&apos;s Description.
        /// </summary>
        public static string DepositDescription {
            get {
                return ResourceManager.GetString("DepositDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit&apos;s ID.
        /// </summary>
        public static string DepositID {
            get {
                return ResourceManager.GetString("DepositID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Search.
        /// </summary>
        public static string DetailedSearch {
            get {
                return ResourceManager.GetString("DetailedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center address.
        /// </summary>
        public static string DistributionCenterAddress {
            get {
                return ResourceManager.GetString("DistributionCenterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center ID.
        /// </summary>
        public static string DistributionCenterID {
            get {
                return ResourceManager.GetString("DistributionCenterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center&apos;s Type.
        /// </summary>
        public static string DistributionCenterTypeID {
            get {
                return ResourceManager.GetString("DistributionCenterTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Center valuation.
        /// </summary>
        public static string DistributionCenterValuation {
            get {
                return ResourceManager.GetString("DistributionCenterValuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Divitions.
        /// </summary>
        public static string DivitionNumber {
            get {
                return ResourceManager.GetString("DivitionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divitions&apos; Width.
        /// </summary>
        public static string DivitionWidth {
            get {
                return ResourceManager.GetString("DivitionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifo.
        /// </summary>
        public static string Fifo {
            get {
                return ResourceManager.GetString("Fifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        public static string FileNumber {
            get {
                return ResourceManager.GetString("FileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Number.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Floors.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Description.
        /// </summary>
        public static string HallDescription {
            get {
                return ResourceManager.GetString("HallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall&apos;s ID.
        /// </summary>
        public static string HallID {
            get {
                return ResourceManager.GetString("HallID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halls.
        /// </summary>
        public static string Halls {
            get {
                return ResourceManager.GetString("Halls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Expiration Date.
        /// </summary>
        public static string HasExpirationDate {
            get {
                return ResourceManager.GetString("HasExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Maximum Capacity.
        /// </summary>
        public static string HasMaxCapacity {
            get {
                return ResourceManager.GetString("HasMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Max Order&apos;s Total.
        /// </summary>
        public static string HasMaxOrderTotal {
            get {
                return ResourceManager.GetString("HasMaxOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Max Product Price.
        /// </summary>
        public static string HasMaxProductPrice {
            get {
                return ResourceManager.GetString("HasMaxProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Min Order&apos;s Total.
        /// </summary>
        public static string HasMinOrderTotal {
            get {
                return ResourceManager.GetString("HasMinOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Min Product Price.
        /// </summary>
        public static string HasMinProductPrice {
            get {
                return ResourceManager.GetString("HasMinProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Minimum Stock.
        /// </summary>
        public static string HasMinStock {
            get {
                return ResourceManager.GetString("HasMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Minimum Digits.
        /// </summary>
        public static string HasPasswordDigits {
            get {
                return ResourceManager.GetString("HasPasswordDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Minimum Lowecase Characters.
        /// </summary>
        public static string HasPasswordLower {
            get {
                return ResourceManager.GetString("HasPasswordLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Maximum Lenght.
        /// </summary>
        public static string HasPasswordMax {
            get {
                return ResourceManager.GetString("HasPasswordMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Minimum Lenght.
        /// </summary>
        public static string HasPasswordMin {
            get {
                return ResourceManager.GetString("HasPasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Minimum Symbols.
        /// </summary>
        public static string HasPasswordSymbols {
            get {
                return ResourceManager.GetString("HasPasswordSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password&apos;s Minimum Upercase Characters.
        /// </summary>
        public static string HasPasswordUpper {
            get {
                return ResourceManager.GetString("HasPasswordUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Usernames&apos;s Minimum Digits.
        /// </summary>
        public static string HasUsernameDigits {
            get {
                return ResourceManager.GetString("HasUsernameDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Username&apos;s Minimum Lowecase Characters.
        /// </summary>
        public static string HasUsernameLower {
            get {
                return ResourceManager.GetString("HasUsernameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Username&apos;s Maximum Lenght.
        /// </summary>
        public static string HasUsernameMax {
            get {
                return ResourceManager.GetString("HasUsernameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Username&apos;s Minimum Lenght.
        /// </summary>
        public static string HasUsernameMin {
            get {
                return ResourceManager.GetString("HasUsernameMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Usernames&apos;s Minimum Symbols.
        /// </summary>
        public static string HasUsernameSymbols {
            get {
                return ResourceManager.GetString("HasUsernameSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Usernames&apos;s Minimum Upercase Characters.
        /// </summary>
        public static string HasUsernameUpper {
            get {
                return ResourceManager.GetString("HasUsernameUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Subdivision ID.
        /// </summary>
        public static string IDShelfSubdivision {
            get {
                return ResourceManager.GetString("IDShelfSubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a basic Product?.
        /// </summary>
        public static string IsBasic {
            get {
                return ResourceManager.GetString("IsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a sale?.
        /// </summary>
        public static string IsSale {
            get {
                return ResourceManager.GetString("IsSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Waste.
        /// </summary>
        public static string IsWaste {
            get {
                return ResourceManager.GetString("IsWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity.
        /// </summary>
        public static string ItemQty {
            get {
                return ResourceManager.GetString("ItemQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Per Box.
        /// </summary>
        public static string ItemsPerBox {
            get {
                return ResourceManager.GetString("ItemsPerBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA.
        /// </summary>
        public static string Iva {
            get {
                return ResourceManager.GetString("Iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Depth.
        /// </summary>
        public static string MaxDepth {
            get {
                return ResourceManager.GetString("MaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Height.
        /// </summary>
        public static string MaxHeight {
            get {
                return ResourceManager.GetString("MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Order&apos;s Total.
        /// </summary>
        public static string MaxOrderTotal {
            get {
                return ResourceManager.GetString("MaxOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Product Price.
        /// </summary>
        public static string MaxProductPrice {
            get {
                return ResourceManager.GetString("MaxProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Size.
        /// </summary>
        public static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Width.
        /// </summary>
        public static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Order&apos;s Total.
        /// </summary>
        public static string MinOrderTotal {
            get {
                return ResourceManager.GetString("MinOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Product Price.
        /// </summary>
        public static string MinProductPrice {
            get {
                return ResourceManager.GetString("MinProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Stock Quantity.
        /// </summary>
        public static string MinStock {
            get {
                return ResourceManager.GetString("MinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/Reference.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack&apos;s ID.
        /// </summary>
        public static string PackID {
            get {
                return ResourceManager.GetString("PackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack&apos;s Code.
        /// </summary>
        public static string PackSerialCode {
            get {
                return ResourceManager.GetString("PackSerialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Minimum Digits.
        /// </summary>
        public static string PasswordDigits {
            get {
                return ResourceManager.GetString("PasswordDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Minimum Lowercase Characters.
        /// </summary>
        public static string PasswordLower {
            get {
                return ResourceManager.GetString("PasswordLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Maximum Lenght.
        /// </summary>
        public static string PasswordMax {
            get {
                return ResourceManager.GetString("PasswordMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Minimum Lenght.
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Minimum Symbols.
        /// </summary>
        public static string PasswordSymbols {
            get {
                return ResourceManager.GetString("PasswordSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s Minimum Upercase Characters.
        /// </summary>
        public static string PasswordUpper {
            get {
                return ResourceManager.GetString("PasswordUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        public static string PhotoPath {
            get {
                return ResourceManager.GetString("PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in the Box.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack&apos;s Code.
        /// </summary>
        public static string RackCode {
            get {
                return ResourceManager.GetString("RackCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack&apos;s Description.
        /// </summary>
        public static string RackDescritpion {
            get {
                return ResourceManager.GetString("RackDescritpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack ID.
        /// </summary>
        public static string RackID {
            get {
                return ResourceManager.GetString("RackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks.
        /// </summary>
        public static string Racks {
            get {
                return ResourceManager.GetString("Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reevaluate?.
        /// </summary>
        public static string Reevaluate {
            get {
                return ResourceManager.GetString("Reevaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Picture.
        /// </summary>
        public static string ReplacePicture {
            get {
                return ResourceManager.GetString("ReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role&apos;s ID.
        /// </summary>
        public static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale&apos;s Date.
        /// </summary>
        public static string SaleDate {
            get {
                return ResourceManager.GetString("SaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale&apos;s ID.
        /// </summary>
        public static string SaleID {
            get {
                return ResourceManager.GetString("SaleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched Item.
        /// </summary>
        public static string SearchID {
            get {
                return ResourceManager.GetString("SearchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector&apos;s Name.
        /// </summary>
        public static string SectorDescription {
            get {
                return ResourceManager.GetString("SectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector ID.
        /// </summary>
        public static string SectorID {
            get {
                return ResourceManager.GetString("SectorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string SellerPrice {
            get {
                return ResourceManager.GetString("SellerPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout.
        /// </summary>
        public static string SessionTime {
            get {
                return ResourceManager.GetString("SessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelfs&apos; Height.
        /// </summary>
        public static string ShelfHeight {
            get {
                return ResourceManager.GetString("ShelfHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelfs.
        /// </summary>
        public static string Shelfs {
            get {
                return ResourceManager.GetString("Shelfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Shelves.
        /// </summary>
        public static string ShelfsNumber {
            get {
                return ResourceManager.GetString("ShelfsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Subdivision Name.
        /// </summary>
        public static string ShelfSubdivisionName {
            get {
                return ResourceManager.GetString("ShelfSubdivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Info.
        /// </summary>
        public static string SizeInfo {
            get {
                return ResourceManager.GetString("SizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State ID.
        /// </summary>
        public static string StateID {
            get {
                return ResourceManager.GetString("StateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Description.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ID.
        /// </summary>
        public static string StatusID {
            get {
                return ResourceManager.GetString("StatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal Price.
        /// </summary>
        public static string SubTotalPrice {
            get {
                return ResourceManager.GetString("SubTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Name.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Product Code.
        /// </summary>
        public static string SuppliersProductCode {
            get {
                return ResourceManager.GetString("SuppliersProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surcharge.
        /// </summary>
        public static string Surcharge {
            get {
                return ResourceManager.GetString("Surcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Phone.
        /// </summary>
        public static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Deposit ID.
        /// </summary>
        public static string TemporaryDepositID {
            get {
                return ResourceManager.GetString("TemporaryDepositID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Deposit Name.
        /// </summary>
        public static string TemporaryDepositName {
            get {
                return ResourceManager.GetString("TemporaryDepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is in Transit.
        /// </summary>
        public static string Transit {
            get {
                return ResourceManager.GetString("Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit&apos;s Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable Space.
        /// </summary>
        public static string UsableSpace {
            get {
                return ResourceManager.GetString("UsableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Space Used.
        /// </summary>
        public static string UsableSpacePercentage {
            get {
                return ResourceManager.GetString("UsableSpacePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable Used Space.
        /// </summary>
        public static string UsableUsedSpace {
            get {
                return ResourceManager.GetString("UsableUsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Space.
        /// </summary>
        public static string UsedPercentage {
            get {
                return ResourceManager.GetString("UsedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Space.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames&apos;s Minimum Digits.
        /// </summary>
        public static string UsernameDigits {
            get {
                return ResourceManager.GetString("UsernameDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames&apos;s Minimum Lowercase Characters.
        /// </summary>
        public static string UsernameLower {
            get {
                return ResourceManager.GetString("UsernameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username&apos;s Maximum Lenght.
        /// </summary>
        public static string UsernameMax {
            get {
                return ResourceManager.GetString("UsernameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username&apos;s Minimum Lenght.
        /// </summary>
        public static string UsernameMin {
            get {
                return ResourceManager.GetString("UsernameMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames&apos;s Minimum Symbols.
        /// </summary>
        public static string UsernameSymbols {
            get {
                return ResourceManager.GetString("UsernameSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames&apos;s Minimum Upercase Characters.
        /// </summary>
        public static string UsernameUpper {
            get {
                return ResourceManager.GetString("UsernameUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted Average.
        /// </summary>
        public static string WeightedAverage {
            get {
                return ResourceManager.GetString("WeightedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
