//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} has been successfully restored.
        /// </summary>
        public static string ActivatedItem {
            get {
                return ResourceManager.GetString("ActivatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} have been successfully activated.
        /// </summary>
        public static string ActivatedItems {
            get {
                return ResourceManager.GetString("ActivatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully canceled.
        /// </summary>
        public static string CancelledItem {
            get {
                return ResourceManager.GetString("CancelledItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} has been successfully markes as inactive.
        /// </summary>
        public static string DeactivatedItem {
            get {
                return ResourceManager.GetString("DeactivatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} have been successfully deactivated.
        /// </summary>
        public static string DeactivatedItems {
            get {
                return ResourceManager.GetString("DeactivatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User with Username: {0} and Filenumber: {1} has been deactivated automatically due to inactivity.
        /// </summary>
        public static string DeactivatedUserNotification {
            get {
                return ResourceManager.GetString("DeactivatedUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} has been successfully deleted.
        /// </summary>
        public static string DeletedItem {
            get {
                return ResourceManager.GetString("DeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found, add it instead.
        /// </summary>
        public static string EditNotFound {
            get {
                return ResourceManager.GetString("EditNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Container {0} was moved to the Temporary Deposit &quot;{1}&quot; (ID: {2}.
        /// </summary>
        public static string EmptyContainerMoved {
            get {
                return ResourceManager.GetString("EmptyContainerMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} has not been found create a new Item if desired.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Javascript in your browser in order to see this page correctly.
        /// </summary>
        public static string JavascriptDeactivated {
            get {
                return ResourceManager.GetString("JavascriptDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in, please wait....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed Successfully.
        /// </summary>
        public static string OperationSuccessfull {
            get {
                return ResourceManager.GetString("OperationSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Changed User Password.
        /// </summary>
        public static string PasswordChangeSuccessfull {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password policy has changed and your password doesn&apos;t meet the specified requirements. Please change your password for a more strong instead..
        /// </summary>
        public static string PasswordsPolicyChange {
            get {
                return ResourceManager.GetString("PasswordsPolicyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order {0} has been recieved in {1}.
        /// </summary>
        public static string ReceptionActivity {
            get {
                return ResourceManager.GetString("ReceptionActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order number {0} from {1} has been recieved..
        /// </summary>
        public static string ReceptionNotification {
            get {
                return ResourceManager.GetString("ReceptionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully restored.
        /// </summary>
        public static string RestoredItem {
            get {
                return ResourceManager.GetString("RestoredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} boxes has been sold to the client {1}.
        /// </summary>
        public static string SaleActivity {
            get {
                return ResourceManager.GetString("SaleActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sale has been annuled.
        /// </summary>
        public static string SaleAnnulated {
            get {
                return ResourceManager.GetString("SaleAnnulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sale has been reapproved.
        /// </summary>
        public static string SaleApproved {
            get {
                return ResourceManager.GetString("SaleApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State/Province.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De you want Penates to show the delete constraints on a Popup?.
        /// </summary>
        public static string ShowConstraintsOnPopup {
            get {
                return ResourceManager.GetString("ShowConstraintsOnPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De you want Penates to show this error on a Popup?.
        /// </summary>
        public static string ShowErrorsOnPopup {
            get {
                return ResourceManager.GetString("ShowErrorsOnPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was added successfully.
        /// </summary>
        public static string SuccessfullAdd {
            get {
                return ResourceManager.GetString("SuccessfullAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was assigned successfully.
        /// </summary>
        public static string SuccessfullAssign {
            get {
                return ResourceManager.GetString("SuccessfullAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was unassigned successfully.
        /// </summary>
        public static string SuccessfullUnassign {
            get {
                return ResourceManager.GetString("SuccessfullUnassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to activate {0}?.
        /// </summary>
        public static string SureToActivate {
            get {
                return ResourceManager.GetString("SureToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add {0}?.
        /// </summary>
        public static string SureToAdd {
            get {
                return ResourceManager.GetString("SureToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel {0}?.
        /// </summary>
        public static string SureToCancel {
            get {
                return ResourceManager.GetString("SureToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate {0}?.
        /// </summary>
        public static string SureToDeactivate {
            get {
                return ResourceManager.GetString("SureToDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}? .
        /// </summary>
        public static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore {0}?.
        /// </summary>
        public static string SureToRestore {
            get {
                return ResourceManager.GetString("SureToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unassign {0} for {1}?.
        /// </summary>
        public static string SureToUnassign {
            get {
                return ResourceManager.GetString("SureToUnassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} boxes recieved in {1} from {2}.
        /// </summary>
        public static string TransferActivity {
            get {
                return ResourceManager.GetString("TransferActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to sign in to use the system&apos;s functionalities.
        /// </summary>
        public static string UnsignedUser {
            get {
                return ResourceManager.GetString("UnsignedUser", resourceCulture);
            }
        }
    }
}
