using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Penates.Utils {
    public enum Sorts {
        DEFAULT = 0,
        ID = 1,
        ID_DESC = 2,
        CATEGORY = 3,
        CATEGORY_DESC = 4,
        BARCODE = 5,
        BARCODE_DESC = 6,
        NAME = 7,
        NAME_DESC = 8,
        ADDRESS = 9,
        ADDRESS_DESC = 10,
        EMAIL = 11,
        EMAIL_DESC = 12,
        DESCRIPTION = 13,
        DESCRIPTION_DESC = 14,
        CAPACITY = 15,
        CAPACITY_DESC = 16,
        FREESPACE = 17,
        FREESPACE_DESC = 18,
        USABLESPACE = 19,
        USABLESPACE_DESC = 20,
        USABLEFREESPACE = 21,
        USABLEFREESPACE_DESC = 22,
        CITY = 23,
        CITY_DESC = 24,
        DELETED = 25,
        DELETED_DESC=26,
        DATE = 27,
        DATE_DESC = 28,
        USEDPERCENT = 29,
        USEDPERCENT_DESC = 30,
        USERNAME = 31,
        USERNAME_DESC=32,
        FLOOR = 33,
        FLOOR_DESC = 34,
        DISTRIBUTION_CENTER = 35,
        DISTRIBUTION_CENTER_DESC = 36,
        USEDSPACE = 37,
        USEDSPACE_DESC = 38,
        CONTAINER_TYPE = 39,
        CONTAINER_TYPE_DESC = 40,
        TEMPORARY_DEPOSIT = 41,
        TEMPORARY_DEPOSIT_DESC = 42,
        SHELF_SUBDIVISION = 43,
        SHELF_SUBDIVISION_DESC = 44,
        CODE = 45,
        CODE_DESC = 46,
        QUANTITY = 47,
        QUANTITY_DESC = 48,
        PRODUCT = 49,
        PRODUCT_DESC = 50,
        STATUS = 51,
        STATUS_DESC = 52,
        SIZE = 53,
        SIZE_DESC = 54,
        BILL = 55,
        BILL_DESC = 56,
        CLIENT = 57,
        CLIENT_DESC = 58,
        CUIT = 59,
        CUIT_DESC = 60,
        MAX_PRICE = 61,
        MAX_PRICE_DESC = 62,
        MIN_PRICE = 63,
        MIN_PRICE_DESC = 64,
        MAX_TOTAL = 65,
        MAX_TOTAL_DESC = 66,
        MIN_TOTAL = 67,
        MIN_TOTAL_DESC = 68
    }
}