//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Errors.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID you were trying to add is null. Make sure you select a value from the search box.
        /// </summary>
        public static string AddIDNull {
            get {
                return ResourceManager.GetString("AddIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products must have a Container Type assigned.
        /// </summary>
        public static string AllProductsMustHaveAContainer {
            get {
                return ResourceManager.GetString("AllProductsMustHaveAContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} allready exists in the system.
        /// </summary>
        public static string AllreadyExists {
            get {
                return ResourceManager.GetString("AllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already been cancelled or does not exist in the Database.
        /// </summary>
        public static string AlreadyCancelledAlert {
            get {
                return ResourceManager.GetString("AlreadyCancelledAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} has already been deleted or does not exist in the Database.
        /// </summary>
        public static string AlreadyDeletedAlert {
            get {
                return ResourceManager.GetString("AlreadyDeletedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not cancelled or does not exist in the Database.
        /// </summary>
        public static string AlreadyRestoredAlert {
            get {
                return ResourceManager.GetString("AlreadyRestoredAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when getting the autogenerated ID when trying to save an object to the Database.
        /// </summary>
        public static string AutonumberedIDError {
            get {
                return ResourceManager.GetString("AutonumberedIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change your own roles.
        /// </summary>
        public static string CantChangeOwnRoles {
            get {
                return ResourceManager.GetString("CantChangeOwnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA verification failed.
        /// </summary>
        public static string CaptchaFailed {
            get {
                return ResourceManager.GetString("CaptchaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA Verification Successfull!.
        /// </summary>
        public static string CaptchaSuccessfull {
            get {
                return ResourceManager.GetString("CaptchaSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to add the child.
        /// </summary>
        public static string ChildAdd {
            get {
                return ResourceManager.GetString("ChildAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container too small for the Selected box size. Container ID .
        /// </summary>
        public static string ContainerTooSmall {
            get {
                return ResourceManager.GetString("ContainerTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter file to convert should not be null.
        /// </summary>
        public static string ConverterFileNull {
            get {
                return ResourceManager.GetString("ConverterFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to access the database. Database could be down or unaccesible..
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of {0} to delete was null.
        /// </summary>
        public static string DeleteIDNull {
            get {
                return ResourceManager.GetString("DeleteIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit Rack&apos;s size, shelfs or divitions numbers because it still has products in it..
        /// </summary>
        public static string EditRackError {
            get {
                return ResourceManager.GetString("EditRackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid External Distribution Center.
        /// </summary>
        public static string ExternalDistributionCenterInvalid {
            get {
                return ResourceManager.GetString("ExternalDistributionCenterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID to add to is null. Enter a {1} ID in the upper textbox to continue.
        /// </summary>
        public static string FilterIDNull {
            get {
                return ResourceManager.GetString("FilterIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the input data..
        /// </summary>
        public static string FormValidationError {
            get {
                return ResourceManager.GetString("FormValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t get or find Category with ID {0}.
        /// </summary>
        public static string GetCategoryNameError {
            get {
                return ResourceManager.GetString("GetCategoryNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID can&apos;t have a null value.
        /// </summary>
        public static string IDNull {
            get {
                return ResourceManager.GetString("IDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password are invalid.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The browser must have JavaScript enabled in order for Penates Inventory System to work correctly.
        /// </summary>
        public static string JavascriptDisabled {
            get {
                return ResourceManager.GetString("JavascriptDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find an empty location in the selected Distribution Center for the requested containers..
        /// </summary>
        public static string LocationMissing {
            get {
                return ResourceManager.GetString("LocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order can not be store in the selected Distribution Center. The followed Product Categories are not present.
        /// </summary>
        public static string MisssingCategoriesError {
            get {
                return ResourceManager.GetString("MisssingCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move {0} to a {1}.
        /// </summary>
        public static string MovementError {
            get {
                return ResourceManager.GetString("MovementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Size assigned is too small. Free space in order to reduce the size..
        /// </summary>
        public static string NewSpaceTooSmall {
            get {
                return ResourceManager.GetString("NewSpaceTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Size assigned is too small. Space should be grater than {0}.
        /// </summary>
        public static string NewSpaceTooSmallWSize {
            get {
                return ResourceManager.GetString("NewSpaceTooSmallWSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System could not find a location with the requested charasteristics.
        /// </summary>
        public static string NoLocationError {
            get {
                return ResourceManager.GetString("NoLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough containers of type.
        /// </summary>
        public static string NotEnoughContainers {
            get {
                return ResourceManager.GetString("NotEnoughContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an internal calculation problem with the amount of boxes that can be assigned to the selected container type. The recieved boxes don&apos;t feet int the cointeners requested..
        /// </summary>
        public static string NotEnoughContainersForAllBoxes {
            get {
                return ResourceManager.GetString("NotEnoughContainersForAllBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space in the selected Distribution Ceneter. .
        /// </summary>
        public static string NotEnoughSpace {
            get {
                return ResourceManager.GetString("NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation did not terminate correctly.
        /// </summary>
        public static string OperationUnsaccessfull {
            get {
                return ResourceManager.GetString("OperationUnsaccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Order it&apos;s already Processed .
        /// </summary>
        public static string OrderAlreadyProcessed {
            get {
                return ResourceManager.GetString("OrderAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to add the parent.
        /// </summary>
        public static string ParentAdd {
            get {
                return ResourceManager.GetString("ParentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem saving reception to Database.
        /// </summary>
        public static string ReceptionDBError {
            get {
                return ResourceManager.GetString("ReceptionDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the amount of requested containers. Verify it is not 0. .
        /// </summary>
        public static string RequestedContainersError {
            get {
                return ResourceManager.GetString("RequestedContainersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id from {0} is not a valid ID or is null.
        /// </summary>
        public static string SearchIDError {
            get {
                return ResourceManager.GetString("SearchIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to access the security settings, please try again later..
        /// </summary>
        public static string SecurityParametersError {
            get {
                return ResourceManager.GetString("SecurityParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction executed by the Stored Procedure could not be completed. The Stored Procedure returned an error state..
        /// </summary>
        public static string SPError {
            get {
                return ResourceManager.GetString("SPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already been deleted or can&apos;t be deleted from the Database.
        /// </summary>
        public static string UnassignUnsaccessfull {
            get {
                return ResourceManager.GetString("UnassignUnsaccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong request. There are not Temporary Deposit in External Distribution Centers.
        /// </summary>
        public static string WrongRequest {
            get {
                return ResourceManager.GetString("WrongRequest", resourceCulture);
            }
        }
    }
}
