//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Errors.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to activate {0} with ID: {1}.
        /// </summary>
        public static string ActivateException {
            get {
                return ResourceManager.GetString("ActivateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to add a {0} to a {1}.
        /// </summary>
        public static string AddException {
            get {
                return ResourceManager.GetString("AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Box with ID: &quot;{0}&quot; has allready been sold.
        /// </summary>
        public static string BoxAllreadySoldException {
            get {
                return ResourceManager.GetString("BoxAllreadySoldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to deactivate {0} with ID: {1}.
        /// </summary>
        public static string DeactivateException {
            get {
                return ResourceManager.GetString("DeactivateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} still has {1} associated to it and can&apos;t be deleted. Delete {2} first in order to delete it successfully..
        /// </summary>
        public static string DeleteConstraintMessage {
            get {
                return ResourceManager.GetString("DeleteConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to delete {0} with ID {1} from the database.
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to delete {0} from the system.
        /// </summary>
        public static string DeleteExceptionNoID {
            get {
                return ResourceManager.GetString("DeleteExceptionNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with ID &apos;{1}&apos; does not exist as a valid {0} in the database..
        /// </summary>
        public static string ForeignKeyConstraintException {
            get {
                return ResourceManager.GetString("ForeignKeyConstraintException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to get constrains for {0} with ID: &apos;{1}&apos;.
        /// </summary>
        public static string GetConstraintException {
            get {
                return ResourceManager.GetString("GetConstraintException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a parent in the Hierarchy of {1}. This would form a cicular hierarchy dependency!.
        /// </summary>
        public static string HierarchyChildExceptionCircularMessage {
            get {
                return ResourceManager.GetString("HierarchyChildExceptionCircularMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a child of {1}.
        /// </summary>
        public static string HierarchyChildExceptionMessage {
            get {
                return ResourceManager.GetString("HierarchyChildExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Hierarchy Exception.
        /// </summary>
        public static string HierarchyExceptionTitle {
            get {
                return ResourceManager.GetString("HierarchyExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a child in the Hierarchy of {1}. This would form a cicular hierarchy dependency!.
        /// </summary>
        public static string HierarchyParentExceptionCircularMessage {
            get {
                return ResourceManager.GetString("HierarchyParentExceptionCircularMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a parent of {1}.
        /// </summary>
        public static string HierarchyParentExceptionMessage {
            get {
                return ResourceManager.GetString("HierarchyParentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} with ID {1} in the database..
        /// </summary>
        public static string IDNotFoundException {
            get {
                return ResourceManager.GetString("IDNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to retrieve {0} with ID {1} from the database.
        /// </summary>
        public static string InvalidIdSearch {
            get {
                return ResourceManager.GetString("InvalidIdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Exception.
        /// </summary>
        public static string InvalidSortException {
            get {
                return ResourceManager.GetString("InvalidSortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in the database.
        /// </summary>
        public static string ItemAlreadyExist {
            get {
                return ResourceManager.GetString("ItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were trying to  bring the data of {0} with ID={1}, but that {2} was deleted.
        /// </summary>
        public static string ItemDeletedException {
            get {
                return ResourceManager.GetString("ItemDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1} should be set and should not be a null value..
        /// </summary>
        public static string ParametersNulls {
            get {
                return ResourceManager.GetString("ParametersNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to save {0} to the Database.
        /// </summary>
        public static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Executed Stored Procedure returned an error state.
        /// </summary>
        public static string StoredProcedureException {
            get {
                return ResourceManager.GetString("StoredProcedureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no room available in the Temporary Deposits for the Container with ID: {0} to move. The container is now empty and will remain on shelf {1}.
        /// </summary>
        public static string TemporaryDepositsOutOfSpace {
            get {
                return ResourceManager.GetString("TemporaryDepositsOutOfSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to unasigna a {0} from a {1}.
        /// </summary>
        public static string UnassignException {
            get {
                return ResourceManager.GetString("UnassignException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a unique value in the database. The value &apos;{1}&apos; already exists..
        /// </summary>
        public static string UniqueRestrictionException {
            get {
                return ResourceManager.GetString("UniqueRestrictionException", resourceCulture);
            }
        }
    }
}
