//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormsErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Penates.App_Resources.Forms.Model.FormsErrors", typeof(FormsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Barcode should be less than 128 characters long.
        /// </summary>
        public static string BarcodeLength {
            get {
                return ResourceManager.GetString("BarcodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Barcode in order to continue.
        /// </summary>
        public static string BarcodeRequired {
            get {
                return ResourceManager.GetString("BarcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should have a currency format.
        /// </summary>
        public static string CurrencyTypeError {
            get {
                return ResourceManager.GetString("CurrencyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should have a Date Value.
        /// </summary>
        public static string DateTypeError {
            get {
                return ResourceManager.GetString("DateTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description should only be {1} long.
        /// </summary>
        public static string DescriptionLength {
            get {
                return ResourceManager.GetString("DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description should be a text value.
        /// </summary>
        public static string DescriptionType {
            get {
                return ResourceManager.GetString("DescriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too big. It should be less than {1}.
        /// </summary>
        public static string DimentionTooBig {
            get {
                return ResourceManager.GetString("DimentionTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Distribution Center in order to continue.
        /// </summary>
        public static string DistributionCenterRequired {
            get {
                return ResourceManager.GetString("DistributionCenterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a valid Distribution Center in order to continue.
        /// </summary>
        public static string DistributionCenterValid {
            get {
                return ResourceManager.GetString("DistributionCenterValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be a valid email address.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file&apos;s extension for {0} should be of one of the following: {1}.
        /// </summary>
        public static string ExtensionError {
            get {
                return ResourceManager.GetString("ExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Floor Number is to big. {0} only has {1} floors..
        /// </summary>
        public static string FloorTooBig {
            get {
                return ResourceManager.GetString("FloorTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be a value grater or equal to {1}.
        /// </summary>
        public static string GraterOrEqualThanError {
            get {
                return ResourceManager.GetString("GraterOrEqualThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be a value grater than {1}.
        /// </summary>
        public static string GraterThanError {
            get {
                return ResourceManager.GetString("GraterThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you entered is too large, it should be less than 4Mb.
        /// </summary>
        public static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be an integer number.
        /// </summary>
        public static string IntegerError {
            get {
                return ResourceManager.GetString("IntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters. {0} should only have {1}.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}, please choose a diferent username.
        /// </summary>
        public static string IvalidUsername {
            get {
                return ResourceManager.GetString("IvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {0} should be less or equal than {1}.
        /// </summary>
        public static string LenghtError {
            get {
                return ResourceManager.GetString("LenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lenght of the {0} should be at least {1} characters long.
        /// </summary>
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {0} should be less or equal than {1} and grater or equal than {2}.
        /// </summary>
        public static string MinMaxLenghtError {
            get {
                return ResourceManager.GetString("MinMaxLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name should be less than 128 characters long.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Name in order to continue.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should have a numeric value.
        /// </summary>
        public static string NumericTypeError {
            get {
                return ResourceManager.GetString("NumericTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be at least {1} lenght long and have a maximum of {2} characters. It should also have at least {3} lowercase letters, {4} uppercase, {5} digits and {6} symbols.
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain at least 1 upper case character and at least one number or symbol character..
        /// </summary>
        public static string PasswordPolicyError {
            get {
                return ResourceManager.GetString("PasswordPolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new and old passwords should not be the same.
        /// </summary>
        public static string PasswordSameAsOld {
            get {
                return ResourceManager.GetString("PasswordSameAsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should differ from the username.
        /// </summary>
        public static string PasswordSameAsUser {
            get {
                return ResourceManager.GetString("PasswordSameAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be a valid phone number.
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter a valid Id number (Numerica and grater than 0).
        /// </summary>
        public static string ProductIDRange {
            get {
                return ResourceManager.GetString("ProductIDRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Porduct ID in order to continue.
        /// </summary>
        public static string ProductIDRequired {
            get {
                return ResourceManager.GetString("ProductIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be a value between {1} and {2}.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the {0} in order to continue.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the Seller&apos;s Price in order to continue.
        /// </summary>
        public static string SellerPriceRequired {
            get {
                return ResourceManager.GetString("SellerPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter a numeric value as the Seller&apos;s Price.
        /// </summary>
        public static string SellerPriceTypeError {
            get {
                return ResourceManager.GetString("SellerPriceTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should only be {1} long.
        /// </summary>
        public static string StringLenghtError {
            get {
                return ResourceManager.GetString("StringLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should have a text value.
        /// </summary>
        public static string TextTypeError {
            get {
                return ResourceManager.GetString("TextTypeError", resourceCulture);
            }
        }
    }
}
